### ISSUE TITLE
Latest images break Intel acceleration support

### ISSUE THREAD

**Issue by lreeves** [linuxserver/docker-jellyfin#105]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

I believe this is related to https://github.com/linuxserver/docker-jellyfin/pull/102 - but essentially on the latest releases of this image QuickSync encoding fails with the following error:

```
[AVHWDeviceContext @ 0x55d39838b080] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x55d39838b080] Failed to initialise VAAPI connection: -1 (unknown libva error).
```

I believe that the ffmpeg included is compiled against a different version of the VA-API that the Intel packages are using (1.10 versus 1.11) and this breaks both QuickSync and VA-API acceleration. If I downgrade the package used in the container like so:

```
apt install intel-media-va-driver-non-free=21.1.2+i526~u20.04
```

Then everything works as expected again. It's probably easy to pin the version to this but I'm not sure if that's the proper fix versus compiling ffmpeg against the newer libraries. @nyanmisaka - if the former is fine I can whip up a PR, just let me know!

## Environment
**OS:** Docker host is Debian Bullseye
**CPU architecture:** x86_64, Intel i5-11400
**How docker service was installed:**
From the official repo using Docker compose.

## Command used to create docker container (run/create/compose/screenshot)
Docker-compose YAML:
```
---
version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1006
      - PGID=1006
      - TZ=America/New_York
      - LIBVA_DRIVER_NAME=iHD
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    group_add:
      - 105
    volumes:
      - /flash/docker/jellyfin:/config
      - /home/media/share/Television:/data/tvshows:ro
      - /home/media/share/Movies:/data/movies:ro
    ports:
      - 14001:8096
      - 14002:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
```

## Docker logs
```
[AVHWDeviceContext @ 0x55d39838b080] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x55d39838b080] Failed to initialise VAAPI connection: -1 (unknown libva error).
```
