### ISSUE TITLE
h264_v4l2m2m acceleration in Raspberry Pi 4 - 64 bits

### ISSUE THREAD

**Issue by randm-ch** [linuxserver/docker-jellyfin#110]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Good evening! I'm trying to get hardware acceleration to work in the Jellyfin container on a RPi4 64bit OS (Manjaro ARM), so far without luck. As OMX doesn't work on 64bit (and is getting deprecated anyway) it is suggested in different places to use V4L2. This does work with ffmpeg on the host machine without problems (with `ffmpeg -i ... -c:v h264_v4l2m2m ...`), but inside the container it doesn't. I have added devices `/dev/video10` (as well as 11 & 12) to the container.

See also: https://github.com/jellyfin/jellyfin/issues/4892

------------------------------

## Expected Behavior
L4L2 hardware acceleration works.

## Current Behavior
L4L2 hardware acceleration doesn't work. The error is:

```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_v4l2m2m))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_v4l2m2m @ 0xaaaaebe39a00] Using device /dev/video11
[h264_v4l2m2m @ 0xaaaaebe39a00] driver 'bcm2835-codec' on card 'bcm2835-codec-encode' in mplane mode
[h264_v4l2m2m @ 0xaaaaebe39a00] requesting formats: output=YU12 capture=H264
[h264_v4l2m2m @ 0xaaaaebe39a00] Encoder requires yuv420p pixel format.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0xaaaaebe15020] Qavg: 65536.000
[aac @ 0xaaaaebe15020] 2 frames left in the queue on closing
Conversion failed!
```

When trying to run `ffmpeg` manually with `-pix_fmt yuv420p` as suggested in https://github.com/jellyfin/jellyfin/issues/4892 I get this error:

```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_v4l2m2m))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_v4l2m2m @ 0xaaaafae82a00] Using device /dev/video11
[h264_v4l2m2m @ 0xaaaafae82a00] driver 'bcm2835-codec' on card 'bcm2835-codec-encode' in mplane mode
[h264_v4l2m2m @ 0xaaaafae82a00] requesting formats: output=YU12 capture=H264
[h264_v4l2m2m @ 0xaaaafae82a00] Failed to set gop size: Invalid argument
Output #0, hls, to '/config/data/transcodes/224b83dbe3d5c4dd0430795641fcd081.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_v4l2m2m), yuv420p, 3840x2160 [SAR 1:1 DAR 16:9], q=-1--1, 37433 kb/s, 24 fps, 90k tbn, 24 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_v4l2m2m
    Stream #0:1: Audio: aac (LC), 48000 Hz, 5.1, fltp, 640 kb/s (default)
    Metadata:
      encoder         : Lavc58.91.100 aac
[h264_v4l2m2m @ 0xaaaafae82a00] VIDIOC_STREAMON failed on output context
Video encoding failed
[aac @ 0xaaaafae5e020] Qavg: 65536.000
[aac @ 0xaaaafae5e020] 2 frames left in the queue on closing
double free or corruption (out)
Aborted (core dumped)
```

## Steps to Reproduce

1. Start linuxserver/jellyfin docker container on a RPi4 running a 64bit OS, using required devices
2. Configure hardware acceleration in Jellyfin settings, selecting "Exynos L4L2 MFC"
3. Play a video which needs encoding

## Environment
**OS:** Manjaro ARM
**CPU architecture:** arm64
**How docker service was installed:** `ghcr.io/linuxserver/jellyfin` via docker-compose

## Command used to create docker container (run/create/compose/screenshot)

```
services:

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
      TZ: "${TIMEZONE}"
      JELLYFIN_PublishedServerUrl: "${HOST_NAME}:8096"
    ports:
      - "8096:8096"
    volumes:
      - "${VOLUMES_DIR}/jellyfin:/config"
      - "${STORAGE_DIR}:/data"
    devices:
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
      - "/dev/video12:/dev/video12"
```

## Docker logs

https://gist.github.com/randm-ch/285b175f95dac3fd02c3de3f86728c05
