### ISSUE TITLE
Opened issue in "jellyfin-plugin-webhook," but wanted to share here in case.

### ISSUE THREAD

**Issue by nothing2obvi** [linuxserver/docker-jellyfin#128]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I was using 10.7.7 before 10.8.0 and the webhook plugin worked fine -- except I wasn't getting any "ItemAdded" notifications. Installed 10.8.0, and now I see an error I have not seen before, and am not getting any webhook notifications at all. I also opened this issue in [jellyfin-plugin-webhook (#73)](https://github.com/jellyfin/jellyfin-plugin-webhook/issues/73).

```
today at 9:35:01 AM [09:35:01] [ERR] [88] Jellyfin.Plugin.Webhook.WebhookSender: Unable to send notification
today at 9:35:01 AM System.TypeLoadException: Could not load type 'MediaBrowser.Common.Json.JsonDefaults' from assembly 'MediaBrowser.Common, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
today at 9:35:01 AM    at Jellyfin.Plugin.Webhook.Destinations.BaseOption.GetMessageBody(Dictionary`2 data)
today at 9:35:01 AM    at Jellyfin.Plugin.Webhook.Destinations.Discord.DiscordClient.SendAsync(DiscordOption options, Dictionary`2 data)
today at 9:35:01 AM    at Jellyfin.Plugin.Webhook.WebhookSender.SendNotification[T](IWebhookClient`1 webhookClient, T option, Dictionary`2 itemData, Type itemType)
```
------------------------------

## Expected Behavior

The webhook notifications should send, and I should receive them in Gotify and Discord.

## Current Behavior

Nothing.

## Steps to Reproduce

1. I think this is self-explanatory, but can elaborate if you would like.

## Environment
**OS:** Ubuntu 20.0.4
**CPU architecture:** x86_64
**How docker service was installed:** via hub.docker.com

## Command used to create docker container (run/create/compose/screenshot)

```
---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:2021.10.20
    container_name: jellyfin
    environment:
      - PUID=8096
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/docker/jellyfin/config:/config
      - /allmyvolumes:/media
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
networks:
  default:
    external: true
    name: lsio
```

## Docker logs

Mentioned above, but can provide more if requested.
