### ISSUE TITLE
Hardware transcoding dosen't work since 10.7.7-1-ls131

### ISSUE THREAD

**Issue by lemystere** [linuxserver/docker-jellyfin#129]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When hardware transcoding is enable in the settings, Jellyfin would transcode medias that need to be transcode or if the user wants to transcode because he wants a lower bitrate.
Note that in the version 10.7.6-1-ls130 it's working perfectly fine.

## Current Behavior

When hardware transcoding is enable, Jellyfin dosen't transcode.

## Steps to Reproduce

1. Install the image : 10.7.7-1-ls136
2. Of course you need to update jellyfin-ffmpeg to the version 4.3.2-1 in your container
3. Enable hardware transcoding in the settings of Jellyfin
4. Force the transcoding when you play a media 

## Environment
**OS:** Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:** With "stacks" on Portainer.

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: Jellyfin
    environment:
      - PUID=1002
      - PGID=100
    volumes:
      - /path to config:/config
      - /path to media:/media
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
    restart: always
```

## FFmpeg logs

```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_qsv) -> h264 (h264_qsv))
  Stream #0:2 -> #0:1 (eac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[AVHWDeviceContext @ 0x55c96f67d040] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x55c96f67d040] Failed to initialise VAAPI connection: -1 (unknown libva error).
Error creating a QSV device
qsv hwaccel requested for input stream #0:0, but cannot be initialized.
[h264_qsv @ 0x55c96f66f680] Error initializing the MFX video decoder: invalid handle (-6)
Error while decoding stream #0:0: Invalid argument
[AVHWDeviceContext @ 0x55c96f70c440] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x55c96f70c440] Failed to initialise VAAPI connection: -1 (unknown libva error).
Error creating a QSV device
qsv hwaccel requested for input stream #0:0, but cannot be initialized.
```
