### ISSUE TITLE
Hardware acceleration broken since 10.7.7-1-ls147 on GB-BACE-3150 / Intel N3150

### ISSUE THREAD

**Issue by u-cav** [linuxserver/docker-jellyfin#141]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When hardware transcoding is enabled, Jellyfin would correctly transcode files.
Note that in the version 10.7.7-1-ls146 it's working perfectly fine.

## Current Behavior

Starting from 10.7.7-1-ls147, hardware transcoding immediately fails. 

It seems to be broken by PR #136, being the only change between 146 and 147 (see [diff](https://github.com/linuxserver/docker-jellyfin/compare/10.7.7-1-ls146...10.7.7-1-ls147))

This error is shown:

Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.

## Steps to Reproduce

1. Have the correct hardware (?)
2. Spin up a jellyfin container using image: ghcr.io/linuxserver/jellyfin:10.7.7-1-ls147
3. Enable transcoding
4. Start a video that needs transcoding, or reduce the quality to trigger it

## Environment
**OS:** Arch Linux
**CPU architecture:** x86_64 Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz
lshw dump: [lshw.txt](https://github.com/linuxserver/docker-jellyfin/files/7904546/lshw.txt)
**How docker service was installed:** 

Docker and docker-compose installed from the distro repo

## Command used to create docker container (run/create/compose/screenshot)

docker-compose snippet:

```
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1004
      - PGID=1001
      - TZ=Europe/Rome
    volumes:
      - ./jellyfin/config:/config
      - (other media volumes)
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```

started with `docker-compose up -d`

## Docker logs

Jellyfin logs extract: [jellyfin_logs.txt](https://github.com/linuxserver/docker-jellyfin/files/7904610/jellyfin_logs.txt)

The same command run inside the container: [ffmpeg_logs.txt](https://github.com/linuxserver/docker-jellyfin/files/7904611/ffmpeg_logs.txt)
