### ISSUE TITLE
40-gid-video won't create and add group to abc

### ISSUE THREAD

**Issue by gauth-fr** [linuxserver/docker-jellyfin#150]
## Expected Behavior
Necessary groups for HW acceleration are create and added to user abc.

## Current Behavior
On my setup (LXC container on proxmox running docker), this is not the case.
`find /dev/dri /dev/dvb /dev/vchiq /dev/vc-mem /dev/video1? -type c -print 2>/dev/null` won't return the devices.
However, checking manually with stats or ls or whatever, they (card0 & renderD128) show as character special file.

## My Bypass
I create a 90-add-group, which is a modified version of 40-gid-video, using find to find regular file then filter in the loop if it's a char special file.
```shell
#!/usr/bin/with-contenv bash

FILES=$(find /dev/dri /dev/dvb /dev/vchiq /dev/vc-mem /dev/video1? -type f -print 2>/dev/null)

for i in $FILES
do
        if [ -c $i ]; then
                VIDEO_GID=$(stat -c '%g' "$i")
                if ! id -G abc | grep -qw "$VIDEO_GID"; then
                        VIDEO_NAME=$(getent group "${VIDEO_GID}" | awk -F: '{print $1}')
                        if [ -z "${VIDEO_NAME}" ]; then
                                VIDEO_NAME="video$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c8)"
                                echo "Creating group $VIDEO_NAME with id $VIDEO_GID"
                                groupadd "$VIDEO_NAME"
                                groupmod -g "$VIDEO_GID" "$VIDEO_NAME"
                        fi
                        echo "Add group $VIDEO_NAME to abc"
                        usermod -a -G "$VIDEO_NAME" abc
                        if [ $(stat -c '%A' "${i}" | cut -b 5,6) != "rw" ]; then
                                echo -e "**** The device ${i} does not have group read/write permissions, which might prevent hardware transcode from functioning correctly. To fix it, you can run the following on your docker host: ****\nsudo chmod g+rw ${i}\n"
                        fi
                fi
        fi
done

```

## Steps to Reproduce
1. connect in the container, then `groups abc`
2. try to transcode fails

## Environment
**OS:** Proxmox / LXC Ubunto 20.04.4
**CPU architecture:** x86_64
**How docker service was installed:** Official repo

## Command used to create docker container (run/create/compose/screenshot)
```yaml
cat docker-compose.yaml
version: "3"

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
     - PUID=$PUID
     - PGID=$PGID
     - TZ=$TZ
    devices:
     - /dev/dri:/dev/dri
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      proxy:
    ports:
      - 8096:8096
    expose:
      - 8096
    volumes:
      - $CONFIGFOLDER/jellyfin/config:/config
      - $CONFIGFOLDER/jellyfin/cache:/cache
      - $LOCAL_MEDIAFOLDER:/data/video

networks:
  proxy:
    external:
      name: proxy
```
## Docker logs (which also contains my custom-cont script)
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Jellyfin: https://opencollective.com/jellyfin

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-gid-video: executing...
[cont-init.d] 40-gid-video: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] files found in /config/custom-cont-init.d executing
[custom-init] 90-add-group: executing...
Creating group videoBHXXyuDV with id 107
Add group videoBHXXyuDV to abc
Add group video to abc
[custom-init] 90-add-group: exited 0
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:06:24] [INF] [1] Main: Jellyfin version: 10.7.7
[12:06:24] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_CONFIG_DIR, /config]"]
[12:06:24] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"]
[12:06:24] [INF] [1] Main: Operating system: Linux
[12:06:24] [INF] [1] Main: Architecture: X64
[12:06:24] [INF] [1] Main: 64-Bit Process: True
[12:06:24] [INF] [1] Main: User Interactive: True
[12:06:24] [INF] [1] Main: Processor count: 2
[12:06:24] [INF] [1] Main: Program data path: /config/data
[12:06:24] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[12:06:24] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
```
