### ISSUE TITLE
Ubuntu 22.04 - "/dev/dri": no such file or directory

### ISSUE THREAD

**Issue by flyingnobita** [linuxserver/docker-jellyfin#165]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
On a host machine with Ubuntu Budgie 20.04 on Intel i5-4200U with Intel HD Graphics 4400, the container was successfully loading devices `/dev/dri:/dev/dri` for HW acceleration.

Upgraded host to Ubuntu 22.04 and expected the same `docker compose` config to work.

## Current Behavior

After the upgrade, starting the container generate the error:

```
Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory
```

## Steps to Reproduce

1. Start with Docker Desktop on Ubuntu 22.04
2. Create a `docker-compose.yml` with:
  ```
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    # user: ubuntu
    # group_add:
    #   - render
    #   - video
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/ubuntu/docker_apps/jellyfin/config:/config
      - /media/nas/Media/Video:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
   ```
3. Start Docker

## Environment
**OS:** Ubuntu 22.04.1
**CPU architecture:** x86_64 - i5-4200U w/ Intel HD Graphics 4400
**How docker service was installed:**

With Docker Desktop for Ubuntu DEB as according to official Docker docs.

## Command used to create docker container (run/create/compose/screenshot)

```
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    # user: ubuntu
    # group_add:
    #   - render
    #   - video
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/ubuntu/docker_apps/jellyfin/config:/config
      - /media/nas/Media/Video:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
```

## Docker logs

None as container was started.

Extra Note:
jellyfin runs fine when none of the 3 /dev/dri lines are included in the docker compose file (albeit w/o HW)

Also tried each of the following but got the same error:
1. running container with default user `ubuntu` that has `render` and `video` group added (by way of `usermod` in host and `group_add` in docker compose file.
2. running 2 above and also changing owner of /dev/dri/* to ubuntu:ubuntu
3. setting 777 to /dev/dri/*
4. running official image `jellyfin/jellyfin:latest` with the documented user permission setup
