### ISSUE TITLE
[BUG] Transcoding fails without `intel-opencl-icd` being installed

### ISSUE THREAD

**Issue by tangowithfoxtrot** [linuxserver/docker-jellyfin#280]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Some transcoded content fails to play with the error shared in the "container logs" section.

When searching this issue, I came across [this comment](https://github.com/jellyfin/jellyfin/issues/13324#issuecomment-2571374483), which suggests installing `intel-opencl-icd` based on the [Jellyfin documentation](https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#configure-on-linux-host).

Once I installed that package in the linuxserver.io Jellyfin container, transcoded playback for that content worked again.

### Expected Behavior

For `intel-opencl-icd` to be installed so that hardware-accelerated video transcoding works.

### Steps To Reproduce

1. On a system with supported Intel hardware acceleration, attempt to playback a 4k file that needs transcoding.
2. Get the aforementioned error (see log dump).

### Environment

```markdown
- OS: NixOS
- How docker service was installed: enabled the NixOS way via: `/etc/nixos/configuration.nix`.
```

### CPU architecture

x86-64

### Docker creation

`compose.yml`:

```yaml
x-defaults:
  environment: &default-env
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}
    UMASK: 002 # https://wiki.servarr.com/docker-guide#umask

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:10.10.4
    container_name: jellyfin
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      <<: *default-env
    volumes:
      - ${DOCKER_STORAGE}/media_server/jellyfin/config:/config
      - ${DOCKER_STORAGE}/media_server/jellyfin/cache:/cache
      - ${DOCKER_STORAGE}/media_server/media:/media
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped
```

### Container logs

```bash
jellyfin  | [08:18:20] [INF] [35] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for USERNAME_REDACTED. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
jellyfin  | [08:18:21] [INF] [27] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
jellyfin  | [08:18:21] [INF] [27] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -f matroska -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/tv/FILENAME_REDACTED.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -preset veryfast -b:v 23579455 -maxrate 23579455 -bufsize 47158910 -profile:v:0 high -level 51 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,hwmap=derive_device=opencl:mode=read,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:mode=write:reverse=1:extra_hw_frames=16,format=qsv" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "4f2cd2cfbd520a7d87821856b3eea958-1.mp4" -start_number 0 -hls_segment_filename "/config/cache/transcodes/4f2cd2cfbd520a7d87821856b3eea958%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/config/cache/transcodes/4f2cd2cfbd520a7d87821856b3eea958.m3u8"
jellyfin  | [08:18:21] [ERR] [27] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 237
jellyfin  | [08:18:21] [ERR] [27] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/3a947d8d-e64b-114a-8e1f-53cb057a79f2/hls1/main/-1.mp4.
```
