### ISSUE TITLE
[BUG] Jellyfin can not see the content of mounted folder, but the container can

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [linuxserver/docker-jellyfin#288]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

My setup is the following:
```yaml
 jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      DOCKER_MODS: lscr.io/linuxserver/mods:jellyfin-amd
      JELLYFIN_PublishedServerUrl: https://stream.${DOMAIN}
    networks:
      services:
    volumes:
      - ${CONFIG_FOLDER}/jellyfin:/config
      - ${FILMS}:/media/films:ro
      - ${SERIES}:/media/series:ro
      - ${MUSIQUE}:/media/musique:ro
      - ${LIVRES}:/media/livres:ro
      - ${TROISD}:/media/troisd:ro
      - ${BONUS}:/media/bonus:ro
      - ${SHORTS}:/media/shorts:ro
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
```
I am trying to add /media/films as a library. When logging into the container's console, I can list all the content of /media/films and see its content. So the container access is correct.

But now, Jellyfin can't see the content when trying to add the library. I am having the following error:
`[21:32:30] [ERR] [11] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find a part of the path '/media/films'. URL GET /Environment/DirectoryContents.`

This seems to be related to the image. Because I tried switching to the officiel image, with the following setup:
```yaml
  jellyfin:
    #image: lscr.io/linuxserver/jellyfin:latest
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      #<<: *all-common
      #PUID: 1000
      #PGID: 1000
      TZ: ${TZ}
      #DOCKER_MODS: lscr.io/linuxserver/mods:jellyfin-amd
      JELLYFIN_PublishedServerUrl: https://stream.${DOMAIN}
    networks:
      services:
    volumes:
      - ${CONFIG_FOLDER}/jellyfin:/config
      - ${FILMS}:/media/films:ro
      - ${SERIES}:/media/series:ro
      - ${MUSIQUE}:/media/musique:ro
      - ${LIVRES}:/media/livres:ro
      - ${TROISD}:/media/troisd:ro
      - ${BONUS}:/media/bonus:ro
      - ${SHORTS}:/media/shorts:ro
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
 ```

This works perfectly. So I am unsure what the problem is but it seems to be only with the linuxserver's image.

Thanks in advance for any answer, have a nice day

### Steps To Reproduce

Install with the following setup:
```yaml
 jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      DOCKER_MODS: lscr.io/linuxserver/mods:jellyfin-amd
      JELLYFIN_PublishedServerUrl: https://stream.${DOMAIN}
    networks:
      services:
    volumes:
      - ${CONFIG_FOLDER}/jellyfin:/config
      - ${FILMS}:/media/films:ro
      - ${SERIES}:/media/series:ro
      - ${MUSIQUE}:/media/musique:ro
      - ${LIVRES}:/media/livres:ro
      - ${TROISD}:/media/troisd:ro
      - ${BONUS}:/media/bonus:ro
      - ${SHORTS}:/media/shorts:ro
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
```

### Environment

```markdown
- OS: Debian
- How docker service was installed: apt install
```

### CPU architecture

x86-64

### Docker creation

```bash
jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      DOCKER_MODS: lscr.io/linuxserver/mods:jellyfin-amd
      JELLYFIN_PublishedServerUrl: https://stream.${DOMAIN}
    networks:
      services:
    volumes:
      - ${CONFIG_FOLDER}/jellyfin:/config
      - ${FILMS}:/media/films:ro
      - ${SERIES}:/media/series:ro
      - ${MUSIQUE}:/media/musique:ro
      - ${LIVRES}:/media/livres:ro
      - ${TROISD}:/media/troisd:ro
      - ${BONUS}:/media/bonus:ro
      - ${SHORTS}:/media/shorts:ro
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
```

### Container logs

```bash
[21:32:30] [ERR] [11] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find a part of the path '/media/films'. URL GET /Environment/DirectoryContents.
```

**Comment by j0nnymoe** [comment]
I'm going to take a guess that your media is on a remote mount and/or uid/gid doesn't have access to your media folders.

Also why would you mount all separate folders within `/media` rather than just doing 1 mount for `/media` folder?

**Comment by LeVraiRoiDHyrule** [comment]
> I'm going to take a guess that your media is on a remote mount and/or uid/gid doesn't have access to your media folders.
> 
> Also why would you mount all separate folders within `/media` rather than just doing 1 mount for `/media` folder?

Hi, thanks for your answer.

I have done `chmod 555` to all my media so it should be accessible for any user, I guess
Plus, I have not done any permission operation between trying with linuxserver's image and jellyfin official image. I have tried again and can confirm that simply changing the used images makes it work / not work.

I am currently organizing my media folders that way. I will optimize that later, after getting it to work.

**Comment by j0nnymoe** [comment]
Comparing our container vs their container (at least your compose for it) - of course theirs is going to work because you have it running as root. 

Your media folders need to be owned by the UID/GID that you're using to deploy the container (and ideally that needs to be a real user on said system) - there's nothing much more to it than that. (Unless you have some funky storage setup)

**Comment by j0nnymoe** [comment]
Also worth noting our appdata compared to the official container isn't interchangeable.

**Comment by LeVraiRoiDHyrule** [comment]
> Also worth noting our appdata compared to the official container isn't interchangeable.

Yes. I delete all the app data when switching images.

I am not sure how this happens inside the container, but wether I am using linuxserver's image or official one, I am always running with
```yaml
      PUID: 1000
      PGID: 1000
```
(I made a mistake when editing the initial container).

With 1000:1000, I still have the same behaviour where official image sees the files but not linuxserver's one.

**Comment by aptalca** [comment]
Post a full docker log

**Comment by LeVraiRoiDHyrule** [comment]
> Post a full docker log

Docker daemon logs while trying to add a library with linuxserver's image with the compose above:
https://privatebin.net/?d377fab04977e873#9tppbm7inEKTLnRgCQX9aoWxoVyyMjSPtnFUHBDFpjza

Container logs while trying to add a library with linuxserver's image with the compose above:
https://privatebin.net/?9cae7465c1463ffe#88juS4aSRoZNJi9FzMfeqkgu97K2xfEGx9PB1jJuGTZD

**Comment by j0nnymoe** [comment]
Your container starts up logs are using 1001 for uid/gid and not the 1000 like you've got in your compose.

**Comment by LeVraiRoiDHyrule** [comment]
> Your container starts up logs are using 1001 for uid/gid and not the 1000 like you've got in your compose.

I tried with both 1000 and 1001 to see if it made a difference, it does not. The behaviour is the same.

**Comment by j0nnymoe** [comment]
I'm out of idea's. This isn't a bug with the container, it's due to how you've got your permissions configured on the host. If it was a bug with the container, we'd have a lot more reports (plus our own instances wouldn't be working).

Following the data you've posted from the start has been conflicting because you're posting 1 set of compose files then claiming/posting another set.

**Comment by aptalca** [comment]
Official jellyfin container does not use PUID/PGID vars so it's running as root for you. It's not a direct comparison. 

If you're using a remote mount, that would explain why root can access but not an unprivileged user.

You are not giving us complete info and it's confusing.

**Comment by LeVraiRoiDHyrule** [comment]
Sorry if there is confusion. I will try to avoid that. Please forget everything I posted earlier, this is the definitive logs and setup I have. The logs are captured with the exact setup I am sending in this message.

This works as expected:
```yaml
x-all-common: &all-common
  PUID: 1000
  PGID: 1000
  TZ: ${TZ}

...

  jellyfin:
    #image: lscr.io/linuxserver/jellyfin:latest
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      <<: *all-common
      JELLYFIN_PublishedServerUrl: https://stream.${DOMAIN}
    networks:
      services:
    volumes:
      - ${CONFIG_FOLDER}/jellyfin:/config
      - ${FILMS}:/media/films:ro
      - ${SERIES}:/media/series:ro
      - ${MUSIQUE}:/media/musique:ro
      - ${LIVRES}:/media/livres:ro
      - ${TROISD}:/media/troisd:ro
      - ${BONUS}:/media/bonus:ro
      - ${SHORTS}:/media/shorts:ro
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
```

This does not work as expected:
```yaml
x-all-common: &all-common
  PUID: 1000
  PGID: 1000
  TZ: ${TZ}

...

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    #image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      <<: *all-common
      JELLYFIN_PublishedServerUrl: https://stream.${DOMAIN}
    networks:
      services:
    volumes:
      - ${CONFIG_FOLDER}/jellyfin:/config
      - ${FILMS}:/media/films:ro
      - ${SERIES}:/media/series:ro
      - ${MUSIQUE}:/media/musique:ro
      - ${LIVRES}:/media/livres:ro
      - ${TROISD}:/media/troisd:ro
      - ${BONUS}:/media/bonus:ro
      - ${SHORTS}:/media/shorts:ro
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
```

It fails with the following logs:
https://privatebin.net/?ebf6ed2bd278a5b2#2ig5z5VVGLYnge51Nd1kxKDt6oWz6GstHffn9cLribAi

The permissions on the media files are as follows: `dr-xr-xr-x 2 1000 1000` (applied with `-R`).
I can confirm that the files can be listed and their content displayed from the console of the container.

Is there enough information or is there something else I should add ?

Thanks in advance for any help,
Have a nice day
