### ISSUE TITLE
Container IP is announced in server discovery 

### ISSUE THREAD

**Issue by Strixx76** [linuxserver/docker-jellyfin#65]
When using server discovery the announced IP of the server is the container IP and not host IP.

After a lot of googling i have solved it by adding an envornrment variable:

```
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.10:8096
```

Should that be added to the documentation?
