### ISSUE TITLE
Transcoding issues with docker

### ISSUE THREAD

**Issue by LegendaryB** [linuxserver/docker-jellyfin#7]
Hi,

I currently have a little bit problems with the hardware acceleration feature. My CPU has an integrated graphics unit and is also supporting VA API.

The problem now occurs when I try to watch a HEVC 10 bit file. The video never plays and shows the loading spinner all the time.

My system:
CPU: Ryzen 2200G
OS: Ubuntu Server 18.04 LTS

Output of the container:
`[20:35:54] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/media/anime movies/No Game No Life Zero.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:1 -map 0:2 -map -0:s -codec:v:0 h264_vaapi  -b:v 139616000 -maxrate 139616000 -bufsize 279232000 -profile:v high -level 41 -force_key_frames "expr:gte(t,n_forced*3)" -vf "format=nv12|vaapi,hwupload" -copyts -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 384000 -af "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/config/data/transcoding-temp/eba010b6d4ae5bbc705e928f52aab244.m3u8" -y "/config/data/transcoding-temp/eba010b6d4ae5bbc705e928f52aab244%d.ts"`

Output of `vainfo` on host: 
```
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Mesa Gallium driver 19.0.2 for AMD RAVEN (DRM 3.23.0, 4.                       15.0-55-generic, LLVM 8.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

My Docker-Compose:
version: "2"
```
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/sdc1/docker/jellyfin/config:/config
      - /mnt/sdb1/jellyfin/:/media
      - /mnt/sdb1/jellyfin/transcode:/transcode
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: always
    privileged: true
```
Notice: Also tried for the devices parameter:
```
/dev/dri/renderD128:/dev/dri/renderD128
/dev/dri/renderD128:/dev/dri
```

I was also trying to execute vainfo in the docker shell but the command is not recognized at all. Do you have any idea to fix this problem?

Kind Regards,
Daniel
