### ISSUE TITLE
linuxserver/jellyfin:10.6.4-1-ls96 broke Intel Quicksync (most likely due to jellyfin-ffmpeg4.3.1-4-focal)

### ISSUE THREAD

**Issue by fightforlife** [linuxserver/docker-jellyfin#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

hardware transcoding using quicksync on Intel platforms should work
last working build: linuxserver/jellyfin:10.6.4-1-ls95 with jellyfin-ffmpeg4.3.1-3-focal

## Current Behavior

hardware transcoding using quicksync on Intel platforms is not working
first non working build: linuxserver/jellyfin:10.6.4-1-ls96 with jellyfin-ffmpeg4.3.1-4-focal

## Steps to Reproduce

1. Run linuxserver/jellyfin:10.6.4-1-ls96 with jellyfin-ffmpeg4.3.1-4-focal
2. activate Intel QS
3. Play any file that needs to be transcoded

Also discussed here: https://github.com/jellyfin/jellyfin-ffmpeg/issues/62

## Environment
**OS:** Ubuntu 20.10
**CPU architecture:** x86_64 Intel J3455
**How docker service was installed:** Using the suplied docker compose including the device configuration /de/dri

## Command used to create docker container (run/create/compose/screenshot)

```
services:
  app:
#    image: ghcr.io/linuxserver/jellyfin
    image: linuxserver/jellyfin:10.6.4-1-ls95
#    image: linuxserver/jellyfin:10.6.4-1-ls96
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - config:/config
      - /mnt/HDD/share:/data
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    
volumes:
  config:
```
## Docker logs

```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_qsv) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, hls, to '/config/data/transcodes/286304083d50f88764ac6e8a54d5dba1.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_qsv), qsv, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 8003 kb/s, 25 fps, 90k tbn, 25 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 8003532/0/8003532 buffer size: 16007064 vbv_delay: N/A
    Stream #0:1: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp, 224 kb/s (default)
    Metadata:
      encoder         : Lavc58.91.100 libmp3lame
[h264_qsv @ 0x559e6f5a2640] Error during encoding: device failed (-17)
Video encoding failed
[libmp3lame @ 0x559e6f7e47c0] 3 frames left in the queue on closing
Conversion failed!
```
